#!/bin/bash
printf "\n"
printf " * dArkOS Documentation:          https://github.com/christianhaitian/darkos/wiki\n"
printf " * Debian Reference:             https://www.debian.org/doc/manuals/debian-reference/index.en.html\n"
printf "\n"
