#!/bin/bash

. /usr/local/bin/buttonmon.sh

echo "VAR=duckstation-min" > /home/ark/.config/KILLIT
sudo systemctl restart killer_daemon.service

filename=$(basename "$3")
filename="${filename%.*}"

directory=$(dirname "$3" | cut -d "/" -f2)

if [ ! -d "/$directory/psx/savestates" ]; then
    mkdir -p "/$directory/psx/savestates"
fi

if [ -d "$HOME/.local/share/duckstation/savestates" ]; then
    rm -rf "$HOME/.local/share/duckstation/savestates"
fi

if [[ $directory == "roms2" ]]; then
 sed -i '/\/roms\//s//\/roms2\//g' $HOME/.local/share/duckstation/settings.ini
else
 sed -i '/\/roms2\//s//\/roms\//g' $HOME/.local/share/duckstation/settings.ini
fi

ln -sfv "/$directory/psx/savestates" "$HOME/.local/share/duckstation/savestates"
ln -sf /opt/inttools/gamecontrollerdb.txt "$HOME/.local/share/gamecontrollerdb.txt"

DEVICE="$(tr -d '\0' < /home/ark/.config/.DEVICE 2>/dev/null)"

# Only apply to miniloong
case "$DEVICE" in
  *miniloong*|*MINILOONG*)
	for status in /sys/class/drm/card*-HDMI-A-*/status; do
	  [ -e "$status" ] || continue
	  if grep -q disconnected "$status"; then
		HDMI_STATUS="disconnected"
		break
	  else
		HDMI_STATUS="connected"
		break
	  fi
	done
    if [ "$HDMI_STATUS" = "connected" ]; then
      sed -i "/Rotation/c\Rotation \= 0" $HOME/.local/share/duckstation/settings.ini
    else
      sed -i "/Rotation/c\Rotation \= Rotate270" $HOME/.local/share/duckstation/settings.ini
    fi
    ;;
  *)
    continue
    ;;
esac

Test_Button_A
if [ "$?" -eq "10" ]; then
  printf "\033c" >> /dev/tty1
  printf "\033[1;33m" >> /dev/tty1
  if [ ! -d "/$directory/psx/duckstation_gamesettings" ]; then
      printf "\n Creating /$directory/psx/duckstation_gamesettings/${filename}.settings.ini" >> /dev/tty1
      mkdir -p "/$directory/psx/duckstation_gamesettings"
  else
      printf "\n /$directory/psx/duckstation_gamesettings/${filename}.settings.ini" >> /dev/tty1
      printf "\n already exist!" >> /dev/tty1
  fi
  sleep 3
  printf "\033c" >> /dev/tty1
  printf "\033[0m" >> /dev/tty1
  if [ ! -f "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" ]; then
      cp "$HOME/.local/share/duckstation/settings.ini" "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini"
  fi
  /opt/duckstation/duckstationsa -fullscreen -- "${3}" > /dev/null 2>&1
else
  if [ -f "/$directory/psx/duckstation_gamesettings/${filename}.settings.ini" ]; then
    /opt/duckstation/duckstationsa -fullscreen -- "${3}" > /dev/null 2>&1
  else
    /opt/duckstation/duckstationsa -fullscreen -- "${3}" > /dev/null 2>&1
  fi
fi

sudo systemctl stop killer_daemon.service
