# data_dir is required and should be an absolute path to a persistent directory
# possible modes: voltage(default) and pmic
[Config]
mode=voltage
data_dir=/home/ark/.config/batteryplus
V_EMPTY_CHG=3400
V_EMPTY_DIS=3250
